server:
  host: ~
  port: ~
  debug: true

verify:
  host: ~
  port: ~

app:
  register:
    cache:
      size: ~
      ttl: ~

  cookie:
    expire: ~

project:
  name: GoodGuy

admin:
  email: ~ # require
  password: ~ # require
